// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source/libdnet/protobuf/account.proto

module account;

import google.protobuf;

enum protocVersion = 3014000;

class AccountMessage
{
    @Proto(1) MessageType type = protoDefaultValue!MessageType;
    @Proto(2) string name = protoDefaultValue!string;
    @Proto(3) bytes additionalData = protoDefaultValue!bytes;

    enum MessageType
    {
        AUTH = 0,
        REGISTRATION = 1,
        DEREG = 2,
        GET_PROFILE_PROPS = 3,
        SET_PROFILE_PROP = 4,
        GET_PROFILE_PROP = 5,
        LOGOUT = 6,
    }
}
