// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source/libdnet/protobuf/channel.proto

module channel;

import google.protobuf;

enum protocVersion = 3014000;

class ChannelMessage
{
    @Proto(1) MessageType type = protoDefaultValue!MessageType;
    @Proto(2) string name = protoDefaultValue!string;
    @Proto(3) string statusCode = protoDefaultValue!string;
    @Proto(4) bytes additionalData = protoDefaultValue!bytes;

    enum MessageType
    {
        CREATE = 0,
        DESTROY = 1,
        JOIN = 2,
        LEAVE = 3,
        SET_PROP = 4,
        GET_PROPS = 5,
        GET_MEMBERS = 6,
        GET_PROP = 7,
        NEW_MESSAGE_ALERT = 8,
    }
}
