// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source/libdnet/protobuf/dnet.proto

module dnet;

import google.protobuf;
import source.libdnet.protobuf.account;
import source.libdnet.protobuf.channel;
import source.libdnet.protobuf.server;
import source.libdnet.protobuf.property;

enum protocVersion = 3014000;

class DNETMessage
{
    @Proto(1) MessageType type = protoDefaultValue!MessageType;
    @Proto(2) bytes content = protoDefaultValue!bytes;

    enum MessageType
    {
        ACCOUNT = 0,
        CHANNEL = 1,
        SERVER = 2,
    }
}
