// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source:  dnet.proto

module dnet;

import google.protobuf;
import  account;
import  channel;
import  server;
import  property;

enum protocVersion = 3014000;

class DNETMessage
{
    @Proto(1) MessageType type = protoDefaultValue!MessageType;
    @Proto(2) bytes content = protoDefaultValue!bytes;

    enum MessageType
    {
        ACCOUNT = 0,
        CHANNEL = 1,
        SERVER = 2,
    }
}
