// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source/libdnet/protobuf/server.proto

module server;

import google.protobuf;

enum protocVersion = 3014000;

class ServerMessage
{
    @Proto(1) MessageType type = protoDefaultValue!MessageType;
    @Proto(2) bytes additionalData = protoDefaultValue!bytes;

    enum MessageType
    {
        LIST_CHANNELS = 0,
        LIST_USERS = 1,
        GET_SERVER_PROPS = 2,
        GET_SERVER_PROP = 3,
        S2S_MESSAGE = 4,
    }
}

class STSMessage
{
}
